;/*FB_PKG_DELIM*/

__d("AdsCanvasElementUpdateDataActionFlux",[],(function(t,n,r,o,a,i){"use strict";a.exports={actionType:"ELEMENT.UPDATE"}}),null);
__d("AdsMessengerPACreationStateQuestionItemsActionFlux",[],(function(t,n,r,o,a,i){"use strict";a.exports={actionType:"ADS_MESSENGER_PA_CREATION_STATE_QUESTION_ITEMS"}}),null);
__d("AdsPerfTiming",["performance"],(function(t,n,r,o,a,i,l){"use strict";var e,s=(e||(e=r("performance"))).timing&&(e||(e=r("performance"))).timing.fetchStart||t._cstart;l.start=s}),98);
__d("isKeyActivation",["Keys"],(function(t,n,r,o,a,i,l){"use strict";function e(e){var t=0,n=e.charCode,o=e.keyCode;return n!=null&&n!==0?t=n:o!=null&&o!==0&&(t=o),[r("Keys").RETURN,r("Keys").SPACE].includes(t)}l.default=e}),98);
__d("KeyActivationToClickHOC.react",["isKeyActivation","react"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react"));function u(e){var t;return t=(function(t){function n(e){var n;return n=t.call(this,e)||this,n.$2=function(e){var t,o=(t=n.props.isKeyActivation)!=null?t:r("isKeyActivation");o(e)&&(e.preventDefault(),e.stopPropagation(),n.$1&&n.$1.click())},n.$3=function(e){n.$1=e},n.$1=null,n}babelHelpers.inheritsLoose(n,t);var o=n.prototype;return o.render=function(){return s.jsx(e,babelHelpers.extends({keyActivationToClickEvent:this.$2,keyActivationToClickRef:this.$3},this.props))},n})(s.Component),t.displayName="KeyActivationToClickHOC",t}l.default=u}),98);
__d("NonFBLinkReferrerProtector",["$","LinkshimHandlerConfig","Parent","URI","cr:5662","setTimeout"],(function(t,n,r,o,a,i){"use strict";var e,l=(e||(e=n("URI"))).goURIOnWindow,s={alreadySetup:!1,originReferrerPolicyClickWithoutLog:function(t){var e=n("$")("meta_referrer");e.content=n("LinkshimHandlerConfig").switched_meta_referrer_policy,n("setTimeout")(function(){e.content=n("LinkshimHandlerConfig").default_meta_referrer_policy},100)},setupDelegation:function(r){if(r===void 0&&(r=!1),document.body==null){if(r)return;n("setTimeout")(function(){s.setupDelegation(!0)},100);return}if(!s.alreadySetup){s.alreadySetup=!0;var t=function(r){var t=s.getMaybeNonFBLinkReferrerJSMode(r.target);if(t){var o=t[0],a=t[1];switch(o){case"origin":s.originReferrerPolicyClickWithoutLog(a);break;case"ie":var i=new(e||(e=n("URI")))(a.href);r.preventDefault(),l(i,window.open("",a.target),!0);break}}};n("cr:5662").listen(document.body,"click",t)}},getMaybeNonFBLinkReferrerJSMode:function(t){var e=n("Parent").byAttribute(t,"data-lnfb-mode");if(e instanceof HTMLAnchorElement){var r=e.getAttribute("data-lnfb-mode");switch(r){case"ie":case"origin":return[r,e];default:return null}}return null}};a.exports=s}),null);
__d("Popup",["isTruthy"],(function(t,n,r,o,a,i,l){function e(e,t,n,o){var a=[];r("isTruthy")(t)&&a.push("width="+t),r("isTruthy")(n)&&a.push("height="+n);var i=document.body;if(i!=null&&t!=null&&t!==0&&n!=null&&n!==0){var l="screenX"in window?window.screenX:window.screenLeft,s="screenY"in window?window.screenY:window.screenTop,u="outerWidth"in window?window.outerWidth:i.clientWidth,c="outerHeight"in window?window.outerHeight:i.clientHeight-22,d=Math.floor(l+(u-t)/2),m=Math.floor(s+(c-n)/2.5);a.push("left="+d),a.push("top="+m)}return a.push("scrollbars"),window.open(e,o!=null&&o!==""?o:"_blank",a.join(","))}l.open=e}),98);
__d("ShimButton.react",["KeyActivationToClickHOC.react","emptyFunction","react"],(function(t,n,r,o,a,i,l){var e=["children","form","inline","keyActivationToClickEvent","keyActivationToClickRef","onRef","pressed","role"],s,u=s||(s=o("react")),c=(function(t){function n(){for(var e,n=arguments.length,r=new Array(n),o=0;o<n;o++)r[o]=arguments[o];return e=t.call.apply(t,[this].concat(r))||this,e.$1=function(t){e.props.keyActivationToClickRef(t),e.props.onRef(t)},babelHelpers.assertThisInitialized(e)||babelHelpers.assertThisInitialized(e)}babelHelpers.inheritsLoose(n,t);var r=n.prototype;return r.render=function(){var t=this.props,n=t.children,r=t.form,o=t.inline,a=t.keyActivationToClickEvent,i=t.keyActivationToClickRef,l=t.onRef,s=t.pressed,c=t.role,d=babelHelpers.objectWithoutPropertiesLoose(t,e),m=o?"span":"div";r==="link"&&(m="a");var p={onKeyDown:a};return u.jsx(m,babelHelpers.extends({},d,{"aria-pressed":s,ref:this.$1,role:c!=null?c:"button"},p,{children:n}))},n})(u.Component);c.defaultProps={form:"none",inline:!1,keyActivationToClickEvent:r("emptyFunction"),keyActivationToClickRef:r("emptyFunction"),onClick:r("emptyFunction"),onRef:r("emptyFunction"),tabIndex:0};var d=r("KeyActivationToClickHOC.react")(c);l.default=d}),98);
__d("XBasicFBNuxDismissController",["XController"],(function(t,n,r,o,a,i){a.exports=n("XController").create("/ajax/megaphone/dismiss_fbnux/",{nux_id:{type:"Int",required:!0}})}),null);
__d("first",[],(function(t,n,r,o,a,i){"use strict";function e(e){for(var t of e)return t;return null}i.default=e}),66);
__d("isFalsey",[],(function(t,n,r,o,a,i){"use strict";function e(e){return e==null||!e}i.default=e}),66);
__d("stringRefShim",["FBLogger"],(function(t,n,r,o,a,i,l){"use strict";var e="__reactShimRefs";function s(t,n){var o;if(typeof n=="string")o=n;else if(typeof n=="number"||typeof n=="boolean")o=""+n;else return n;if(t==null||t===window)return r("FBLogger")("react_www","string_ref_missing_instance").warn("stringRefShim called with invalid instance of window or null"),n;var a=t[e];a==null&&(a={},t[e]=a);var i=a[o];return i==null&&(i=function(n){t.refs[o]=n},a[o]=i),i}l.default=s}),98);