;/*FB_PKG_DELIM*/

__d("PageCometLaunchpointDiscoverRootQuery_facebookRelayOperation",[],(function(t,n,r,o,a,i){a.exports="24821715574183768"}),null);
__d("PagesCometLaunchpointDiscoverQueryFixEnabled.relayprovider",["gkx"],(function(t,n,r,o,a,i,l){"use strict";var e={get:function(){return!!r("gkx")("23810")}};l.default=e}),98);
__d("PageCometLaunchpointDiscoverRootQuery$Parameters",["PageCometLaunchpointDiscoverRootQuery_facebookRelayOperation","PagesCometLaunchpointDiscoverQueryFixEnabled.relayprovider"],(function(t,n,r,o,a,i){"use strict";var e={kind:"PreloadableConcreteRequest",params:{id:n("PageCometLaunchpointDiscoverRootQuery_facebookRelayOperation"),metadata:{},name:"PageCometLaunchpointDiscoverRootQuery",operationKind:"query",text:null,providedVariables:{__relay_internal__pv__PagesCometLaunchpointDiscoverQueryFixEnabledrelayprovider:n("PagesCometLaunchpointDiscoverQueryFixEnabled.relayprovider")}}};a.exports=e}),null);
__d("PageCometLaunchpointLeftNavMenuRootQuery_facebookRelayOperation",[],(function(t,n,r,o,a,i){a.exports="25157152447238868"}),null);
__d("PageCometLaunchpointLeftNavMenuRootQuery$Parameters",["PageCometLaunchpointLeftNavMenuRootQuery_facebookRelayOperation"],(function(t,n,r,o,a,i){"use strict";var e={kind:"PreloadableConcreteRequest",params:{id:n("PageCometLaunchpointLeftNavMenuRootQuery_facebookRelayOperation"),metadata:{},name:"PageCometLaunchpointLeftNavMenuRootQuery",operationKind:"query",text:null}};a.exports=e}),null);
__d("buildPageCometLaunchpointRoute.entrypoint",["JSResourceForInteraction","PageCometLaunchpointLeftNavMenuRootQuery$Parameters","createContentAreaCompoundEntryPointBuilder","gkx"],(function(t,n,r,o,a,i,l){"use strict";var e=r("createContentAreaCompoundEntryPointBuilder")(r("JSResourceForInteraction")("PageCometLaunchpointEntryPointRoot.react").__setRef("buildPageCometLaunchpointRoute.entrypoint"),function(e){var t,o,a=r("gkx")("23808")&&!((t=(o=e.routeProps)==null?void 0:o.enablePagesLaunchpoint)!=null&&t),i=r("gkx")("23809");return{leftNavContainerQueryReference:{parameters:n("PageCometLaunchpointLeftNavMenuRootQuery$Parameters"),variables:{useAdminedPagesForActingAccount:i,useNewPagesYouManage:a||i}}}});l.default=e}),98);
__d("PageCometLaunchpointDiscoverRoot.entrypoint",["JSResourceForInteraction","PageCometLaunchpointDiscoverRootQuery$Parameters","WebPixelRatio","buildPageCometLaunchpointRoute.entrypoint"],(function(t,n,r,o,a,i,l){"use strict";var e=r("buildPageCometLaunchpointRoute.entrypoint")(r("JSResourceForInteraction")("PageCometLaunchpointDiscoverRoot.react").__setRef("PageCometLaunchpointDiscoverRoot.entrypoint"),function(e){return{queries:{pageDiscoverRootQueryReference:{parameters:r("PageCometLaunchpointDiscoverRootQuery$Parameters"),variables:{id:e.routeProps.userID,scale:o("WebPixelRatio").get()}}}}});l.default=e}),98);
__d("PageCometLaunchpointInvitesRootQuery_facebookRelayOperation",[],(function(t,n,r,o,a,i){a.exports="24173735655660973"}),null);
__d("PageCometLaunchpointInvitesRootQuery$Parameters",["PageCometLaunchpointInvitesRootQuery_facebookRelayOperation"],(function(t,n,r,o,a,i){"use strict";var e={kind:"PreloadableConcreteRequest",params:{id:n("PageCometLaunchpointInvitesRootQuery_facebookRelayOperation"),metadata:{},name:"PageCometLaunchpointInvitesRootQuery",operationKind:"query",text:null}};a.exports=e}),null);
__d("PageCometLaunchpointInvitesRoot.entrypoint",["JSResourceForInteraction","PageCometLaunchpointInvitesRootQuery$Parameters","buildPageCometLaunchpointRoute.entrypoint"],(function(t,n,r,o,a,i,l){"use strict";var e=r("buildPageCometLaunchpointRoute.entrypoint")(r("JSResourceForInteraction")("PageCometLaunchpointInvitesRoot.react").__setRef("PageCometLaunchpointInvitesRoot.entrypoint"),function(e){return{queries:{pageCometLaunchpointInvitesRootQueryReference:{parameters:r("PageCometLaunchpointInvitesRootQuery$Parameters"),variables:{id:e.routeProps.userID}}}}});l.default=e}),98);
__d("PagesCometLaunchpointUnifiedQueryPagesListRedesignedQuery_facebookRelayOperation",[],(function(t,n,r,o,a,i){a.exports="24990774670547920"}),null);
__d("PagesCometLaunchpointUnifiedQueryPagesListRedesignedQuery$Parameters",["PagesCometLaunchpointUnifiedQueryPagesListRedesignedQuery_facebookRelayOperation"],(function(t,n,r,o,a,i){"use strict";var e={kind:"PreloadableConcreteRequest",params:{id:n("PagesCometLaunchpointUnifiedQueryPagesListRedesignedQuery_facebookRelayOperation"),metadata:{},name:"PagesCometLaunchpointUnifiedQueryPagesListRedesignedQuery",operationKind:"query",text:null}};a.exports=e}),null);
__d("PagesCometLaunchpointUnifiedQueryPagesListRedesigned.entrypoint",["JSResourceForInteraction","PagesCometLaunchpointUnifiedQueryPagesListRedesignedQuery$Parameters","WebPixelRatio","buildPageCometLaunchpointRoute.entrypoint"],(function(t,n,r,o,a,i,l){"use strict";var e=r("buildPageCometLaunchpointRoute.entrypoint")(r("JSResourceForInteraction")("PagesCometLaunchpointUnifiedQueryPagesListRedesigned.react").__setRef("PagesCometLaunchpointUnifiedQueryPagesListRedesigned.entrypoint"),function(){return{queries:{pagesCometLaunchpointUnifiedQueryPagesListRedesignedQueryRef:{parameters:n("PagesCometLaunchpointUnifiedQueryPagesListRedesignedQuery$Parameters"),variables:{scale:o("WebPixelRatio").get()}}}}});l.default=e}),98);